// The heart of the tour: mounts the REAL Flow editor (the same System/session/
// LayoutController wiring the docs-site embed uses) with an authored,
// explicitly-positioned graph loaded, themed with the flow package's built-in
// Kiberon theme, and driven from the video clock:
//
// - The editor is built asynchronously under a delayRender handle (the image
//   node pack initializes ImageMagick wasm before it can register specs).
// - Scene `actions` fire once as the playhead crosses their scene-fraction:
//   they go through the editor's real stores (selection, tabs, node ports, the
//   graph runner), so the video reads as someone actually using the tool. A
//   render worker cold-starting a chunk mid-scene replays every crossed action
//   in order; runner timing itself is wall/frame-clock, so render with
//   --concurrency=1 when exact run timing matters.
// - `imageNodes` scenes turn the `image.showPreview` system setting on BEFORE
//   anything runs, so every image node captures and shows its intermediate
//   result once the pipeline evaluates.
// - `imagePayoff` overlays the before → after card (pre-generated by
//   `pnpm image-demo` with the same ImageMagick ops the graph performs).
import { useEffect, useRef, useState } from 'react';
import {
  AbsoluteFill,
  Img,
  continueRender,
  delayRender,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig
} from 'remotion';
import '@kiberon-labs/behave-graph-flow/entry.css';
// The AI pack's panel styles (Conversation / Conversations)  emitted as a
// separate stylesheet by its build, not auto-imported by its JS.
import '@kiberon-labs/behave-graph-nodes-ai/ui.css';
import '@fontsource-variable/geist';
import '@fontsource-variable/geist-mono';
import {
  GraphProvider,
  LayoutController,
  System,
  SystemProvider,
  kitchenSinkPlugin,
  localGraphRunnerPlugin,
  type GraphSession
} from '@kiberon-labs/behave-graph-flow';
import {
  DefaultLogger,
  ManualLifecycleEventEmitter,
  registerCoreProfile,
  writeNodeSpecsToJSON,
  type Dependencies
} from '@kiberon-labs/behave-graph';
import { registerAIProfile } from '@kiberon-labs/behave-graph-nodes-ai';
import { aiPlugin } from '@kiberon-labs/behave-graph-nodes-ai/ui';
import { registerProfile as registerImageProfile } from '@kiberon-labs/behave-graph-nodes-image';
import { imagePlugin } from '@kiberon-labs/behave-graph-nodes-image/ui';
import type { EditorSceneSpec, SceneAction } from '../../narration/script';
import { theme } from '../../theme';
import { graphForKey, positionsForKey } from '../graphs';

interface Editor {
  system: System;
  session: GraphSession;
}

// Session facets decorated by plugins / not part of the static session type.
type RunnableSession = GraphSession & {
  runController?: { play(): void };
  selectionStore?: {
    getState(): { setSelectedNodeId(id: string | null): void };
  };
};

function useEditor(scene: EditorSceneSpec): Editor | null {
  const [editor, setEditor] = useState<Editor | null>(null);
  useEffect(() => {
    const handle = delayRender(`editor:${scene.id}`);
    let cancelled = false;
    (async () => {
      let registry = registerCoreProfile({
        nodes: {},
        values: {},
        // Real dependencies (not a cast): the realtime preview runner builds
        // its own Engine from this registry and needs both to construct.
        dependencies: {
          ILifecycleEventEmitter: new ManualLifecycleEventEmitter(),
          ILogger: new DefaultLogger()
        } as Dependencies
      });
      // The image pack awaits ImageMagick wasm before contributing its nodes
      // (this registry is what the LOCAL runner executes with).
      if (scene.imageNodes) registry = await registerImageProfile(registry);
      // The AI pack merges synchronously  display-only in this tour (no key).
      if (scene.aiNodes) registry = registerAIProfile(registry);

      const system = new System({
        values: registry.values,
        specs: writeNodeSpecsToJSON(registry)
      });
      const session = system.createSession('graph');
      system.registerPlugin(kitchenSinkPlugin);
      system.registerPlugin(localGraphRunnerPlugin, { registry });
      if (scene.imageNodes) {
        // The image pack's UI plugin wires the inline node previews: it
        // decorates the system with a RealtimeRunner (a live preview engine
        // built from this registry), registers the image controls/specifics,
        // and contributes the `image.showPreview` setting. Turn that setting
        // on explicitly BEFORE anything evaluates, so every image node
        // captures and shows its intermediate result.
        await system.registerPlugin(imagePlugin, { registry });
        system.setSetting('image.showPreview', true);
      }
      if (scene.aiNodes) {
        // The AI pack's UI plugin provides the chat store + the Conversation /
        // Conversations panels (and the ConversationRuntime that owns them).
        await system.registerPlugin(aiPlugin);
        // The Conversation panel shows a "no agent connected" placeholder until
        // an agent is registered  connect the same one the graph declares so
        // the scripted chat renders.
        (
          system as unknown as {
            chatStore?: {
              getState(): {
                setAgent(agent: {
                  model?: string;
                  systemPrompt?: string;
                }): void;
              };
            };
          }
        ).chatStore
          ?.getState()
          .setAgent({ model: 'claude-sonnet-5' });
      }
      // Scenes that run a graph: slow the runner down so per-node execution
      // reads on camera (the editor's own pacing setting), and turn on the
      // runner's tracing toggle so spans reach the traces panel and drive the
      // execution highlight.
      if (scene.stepDelayMs) {
        const sys = system as unknown as {
          localGraphRunnerStore?: {
            getState(): {
              setStepDelay(ms: number): void;
              setTickInterval(ms: number): void;
            };
          };
          runner?: {
            store: { getState(): { setEnableTracing(on: boolean): void } };
          };
        };
        sys.localGraphRunnerStore?.getState().setStepDelay(scene.stepDelayMs);
        if (scene.tickIntervalMs) {
          sys.localGraphRunnerStore
            ?.getState()
            .setTickInterval(scene.tickIntervalMs);
        }
        sys.runner?.store.getState().setEnableTracing(true);
      }
      session.flowStore
        .getState()
        .setGraph(graphForKey(scene.graphKey) as never);

      if (!cancelled) setEditor({ system, session });
      continueRender(handle);
    })().catch((err) => {
      // Fail visibly in the studio, but never wedge the render on a handle.
      console.error(`editor scene "${scene.id}" failed to build`, err);
      continueRender(handle);
    });
    return () => {
      cancelled = true;
    };
    // Scenes are static specs; the editor is built once per mount.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return editor;
}

/** Apply one scripted interaction through the editor's real stores. */
function runAction(editor: Editor, action: SceneAction) {
  const session = editor.session as RunnableSession;
  switch (action.do) {
    case 'play':
      session.runController?.play();
      break;
    case 'openTab':
      editor.system.tabStore.getState().openTab(action.tab);
      break;
    case 'nudge':
      // Identity write: wakes every nodeStore subscriber (notably the realtime
      // preview runner's re-evaluate) without changing anything visible.
      session.nodeStore.getState().setNodes((nodes) => [...nodes]);
      break;
    case 'splitLeft':
      // The kitchen-sink default layout, with the left sidebar split into two
      // stacked panels so both requested tabs are visible simultaneously.
      editor.system.tabStore.getState().setLayout({
        dockbox: {
          mode: 'vertical',
          children: [
            {
              mode: 'horizontal',
              children: [
                {
                  size: 2,
                  mode: 'vertical',
                  children: [
                    {
                      mode: 'horizontal',
                      children: [
                        {
                          size: 3,
                          mode: 'vertical',
                          children: [
                            { size: 1, tabs: [{ id: action.tabs[0] }] },
                            { size: 1, tabs: [{ id: action.tabs[1] }] }
                          ]
                        },
                        {
                          size: 17,
                          mode: 'vertical',
                          children: [
                            {
                              id: 'graphs',
                              size: 700,
                              group: 'graph',
                              tabs: [{ id: 'graph' }]
                            }
                          ]
                        },
                        {
                          size: 4,
                          mode: 'vertical',
                          children: [
                            {
                              size: 12,
                              tabs: [
                                { id: 'nodeInputs' },
                                { id: 'system:settings' }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      } as never);
      break;
    case 'chat':
      // Recorded in AppliedState and rendered by enforceChats  the AI pack's
      // ConversationRuntime re-renders the chat store from its own state
      // (wiping ad-hoc messages), so scripted chat must be re-asserted like
      // every other piece of state the editor owns.
      break;
    case 'selectNode':
      session.selectionStore?.getState().setSelectedNodeId(action.nodeId);
      session.nodeStore
        .getState()
        .setNodes((nodes) =>
          nodes.map((n) => ({ ...n, selected: n.id === action.nodeId }))
        );
      break;
    case 'setParam':
      session.nodeStore.getState().setNodes((nodes) =>
        nodes.map((n) =>
          n.id === action.nodeId
            ? {
              ...n,
              data: {
                ...n.data,
                ports: {
                  ...(n.data as { ports?: Record<string, unknown> }).ports,
                  [action.port]: action.value
                }
              }
            }
            : n
        )
      );
      break;
  }
}

function ImagePayoff() {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const inAt = durationInFrames * 0.55;
  const opacity = interpolate(frame, [inAt, inAt + fps * 0.6], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });
  const pane: React.CSSProperties = {
    width: 340,
    height: 255,
    objectFit: 'cover',
    background: theme.bgDeep,
    borderRadius: 12,
    border: `1px solid ${theme.violet}55`
  };
  return (
    <div
      style={{
        position: 'absolute',
        right: 56,
        top: 96,
        zIndex: 1000,
        display: 'flex',
        alignItems: 'center',
        gap: 22,
        padding: 24,
        borderRadius: 16,
        opacity,
        background: 'rgba(10, 9, 18, 0.92)',
        border: `1px solid ${theme.violet}66`,
        boxShadow: `0 20px 70px rgba(0, 0, 0, 0.6), 0 0 60px ${theme.violet}33`,
        color: theme.text,
        fontFamily: theme.font
      }}
    >
      <figure style={{ margin: 0, textAlign: 'center' }}>
        <Img src={staticFile('image-demo/source.png')} style={pane} />
        <figcaption style={{ marginTop: 10, fontSize: 22, color: theme.muted }}>
          before
        </figcaption>
      </figure>
      <div style={{ fontSize: 44, color: theme.accentSoft }}>→</div>
      <figure style={{ margin: 0, textAlign: 'center' }}>
        <Img src={staticFile('image-demo/after.png')} style={pane} />
        <figcaption
          style={{ marginTop: 10, fontSize: 22, color: theme.accentSoft }}
        >
          after  resize · oil-paint · sepia
        </figcaption>
      </figure>
    </div>
  );
}

/** What the video has "typed into" the editor so far  re-asserted whenever the
 *  editor's own machinery (graph reloads, fresh setNodes) would wipe it. */
interface AppliedState {
  selected: string | null;
  params: Array<{ nodeId: string; port: string; value: unknown }>;
  /** Node currently shown as executing (the video's own execution cursor). */
  cursor: string | null;
  /** Scripted conversation-panel messages, in send order. */
  chats: Array<{ role: 'user' | 'assistant'; content: string }>;
}

/** The chat store the AI pack's Conversation panel renders. */
interface ChatStoreLike {
  getState(): {
    messages: Array<{ id: string }>;
    addMessage(message: {
      id: string;
      role: 'user' | 'assistant' | 'system';
      content: string;
      timestamp: Date;
    }): void;
  };
  subscribe(listener: () => void): () => void;
}

/**
 * Re-add any scripted chat message that's gone missing (the ConversationRuntime
 * re-renders the store from its own conversation state and drops ad-hoc
 * entries). Deterministic ids make this idempotent and loop-safe.
 */
function enforceChats(chatStore: ChatStoreLike, chats: AppliedState['chats']) {
  chats.forEach((chat, i) => {
    const id = `video-chat-${i}`;
    // Re-read per message: addMessage re-enters this function synchronously
    // via the store subscription, so a single stale snapshot would double-add.
    const state = chatStore.getState();
    if (!state.messages.some((m) => m.id === id)) {
      state.addMessage({
        id,
        role: chat.role,
        content: chat.content,
        timestamp: new Date()
      });
    }
  });
}

/**
 * Idempotently re-assert everything STATE-shaped: authored node positions (the
 * editor's mount path round-trips the graph through flowToBehave, which drops
 * position metadata and re-runs auto-layout), the current selection, and any
 * edited params. Safe to call from a store subscription  it bails without
 * writing when everything already matches.
 */
function enforceSceneState(
  editor: Editor,
  graphKey: string,
  applied: AppliedState
) {
  const session = editor.session as RunnableSession;
  const desired = positionsForKey(graphKey);
  const nodes = editor.session.nodeStore.getState().nodes;
  const misplaced = nodes.some((n) => {
    const p = desired[n.id];
    return p && (n.position.x !== p.x || n.position.y !== p.y);
  });
  const wantSelected = applied.selected;
  const unselected =
    wantSelected !== null &&
    !nodes.some((n) => n.id === wantSelected && n.selected);
  const stale = applied.params.some((p) => {
    const n = nodes.find((x) => x.id === p.nodeId);
    const ports = (n?.data as { ports?: Record<string, unknown> } | undefined)
      ?.ports;
    return n && ports?.[p.port] !== p.value;
  });
  // The runner's own executing-flush clears the annotation every animation
  // frame (start+end pairs batch together), so the cursor must be re-asserted
  // here too  the subscription makes ours the last write.
  const cursorMismatch = nodes.some((n) => {
    const on =
      (n.data as { annotations?: Record<string, unknown> }).annotations?.[
      'ui.executing'
      ] === true;
    return on !== (applied.cursor !== null && n.id === applied.cursor);
  });

  if (misplaced || unselected || stale || cursorMismatch) {
    editor.session.nodeStore.getState().setNodes((existing) =>
      existing.map((n) => {
        let next = desired[n.id] ? { ...n, position: desired[n.id] } : n;
        if (wantSelected !== null) {
          next = { ...next, selected: n.id === wantSelected };
        }
        for (const p of applied.params) {
          if (p.nodeId === n.id) {
            next = {
              ...next,
              data: {
                ...next.data,
                ports: {
                  ...(next.data as { ports?: Record<string, unknown> }).ports,
                  [p.port]: p.value
                }
              }
            };
          }
        }
        const nextData = next.data as {
          annotations?: Record<string, unknown>;
        };
        const wantOn = applied.cursor !== null && n.id === applied.cursor;
        if ((nextData.annotations?.['ui.executing'] === true) !== wantOn) {
          next = {
            ...next,
            data: {
              ...next.data,
              annotations: { ...nextData.annotations, 'ui.executing': wantOn }
            }
          };
        }
        return next;
      })
    );
    if (unselected) {
      session.selectionStore?.getState().setSelectedNodeId(wantSelected);
    }
  }
}

export function EditorScene({
  scene,
  durationInFrames
}: {
  scene: EditorSceneSpec;
  durationInFrames: number;
}) {
  const frame = useCurrentFrame();
  const editor = useEditor(scene);

  const nextAction = useRef(0);
  const applied = useRef<AppliedState>({
    selected: null,
    params: [],
    cursor: null,
    chats: []
  });

  // Enforcement must react to the editor's OWN store writes too  Flow's mount
  // path re-lays-out after our effects in single-frame renders (stills, the
  // Thumbnail)  so subscribe to the node store and re-assert immediately.
  useEffect(() => {
    if (!editor) return;
    const enforce = () =>
      enforceSceneState(editor, scene.graphKey, applied.current);
    enforce();
    const unsubscribe = editor.session.nodeStore.subscribe(enforce);
    return unsubscribe;
  }, [editor, scene.graphKey]);

  // Scripted chat likewise: the ConversationRuntime re-renders the chat store
  // from its own state (wiping ad-hoc messages), so re-assert ours whenever
  // the store changes.
  useEffect(() => {
    if (!editor || !scene.aiNodes) return;
    const chatStore = (
      editor.system as unknown as { chatStore?: ChatStoreLike }
    ).chatStore;
    if (!chatStore) return;
    const enforce = () => enforceChats(chatStore, applied.current.chats);
    enforce();
    const unsubscribe = chatStore.subscribe(enforce);
    return unsubscribe;
  }, [editor, scene.aiNodes]);

  // Per-frame drive: one-shot actions (play, openTab, selections, edits) fire
  // exactly once as the playhead crosses their mark  a cold-started render
  // chunk replays the whole prefix in order.
  useEffect(() => {
    if (!editor) return;
    const session = editor.session as RunnableSession;

    if (scene.actions) {
      let fired = false;
      while (
        nextAction.current < scene.actions.length &&
        frame >= scene.actions[nextAction.current].at * durationInFrames
      ) {
        const action = scene.actions[nextAction.current];
        runAction(editor, action);
        if (action.do === 'selectNode') {
          applied.current.selected = action.nodeId;
        }
        if (action.do === 'setParam') applied.current.params.push(action);
        if (action.do === 'chat') applied.current.chats.push(action);
        nextAction.current += 1;
        fired = true;
      }
      if (fired) {
        enforceSceneState(editor, scene.graphKey, applied.current);
        const chatStore = (
          editor.system as unknown as { chatStore?: ChatStoreLike }
        ).chatStore;
        if (chatStore) enforceChats(chatStore, applied.current.chats);
      }
    }

    // Execution cursor: light up the node of the most recent trace span. Real
    // node executions are sub-millisecond, so the editor's built-in executing
    // flash never survives a captured frame  re-derive it from the trace
    // collector and let enforceSceneState assert the 'ui.executing' annotation
    // (via the store subscription, so ours outlasts the runner's own flush).
    if (scene.stepDelayMs) {
      const collector = editor.session.traceStore.getState().collector;
      let latest: { nodeId: string; start: number } | null = null;
      for (let i = 0; i < collector.size; i++) {
        const span = collector.spans[i];
        if (span && (!latest || span.start > latest.start)) latest = span;
      }
      const cursor = latest?.nodeId ?? null;
      if (cursor !== applied.current.cursor) {
        applied.current.cursor = cursor;
        enforceSceneState(editor, scene.graphKey, applied.current);
      }
    }

    // Keep the camera fitted to the graph every frame (instant, deterministic;
    // also re-frames when image previews expand their nodes mid-scene).
    session.refStore
      .getState()
      .getRef('reactflow')
      ?.fitView({ padding: 0.15, includeHiddenNodes: true });
  }, [editor, frame, scene, durationInFrames]);

  return (
    <AbsoluteFill style={{ background: theme.bg }}>
      {editor ? (
        <div
          data-flow-theme="kiberon"
          style={{
            width: '100%',
            height: '100%',
            fontFamily: theme.font,
            ['--ds-font-ui' as string]: theme.font,
            ['--ds-font-mono' as string]: theme.mono
          }}
        >
          <SystemProvider value={editor.system}>
            <GraphProvider value={editor.session}>
              <LayoutController />
            </GraphProvider>
          </SystemProvider>
        </div>
      ) : null}
      {scene.imagePayoff ? <ImagePayoff /> : null}
    </AbsoluteFill>
  );
}
